### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by JoelMon** [JoelMon/scriptx#31]
Not all videos have the correct meta data causing the program to crash. Improve the error handling for better user experience.

See issue #30.

**Comment by Lambda-Logan** [comment]
Hi there! I'd love to contribute. I just updated my profile to have my email; I'd really like to arrange a call to better understand the needs of the project. Shoot me an email :-)

**Comment by JoelMon** [comment]
Hello bud!

Sorry that I took long to reply, was out on a little trip to the mountains with the wify. I'll email you soon.

**Comment by JoelMon** [comment]
Closed with f8a78c29db5fd5de86f5ce3138465cfa3deb2d63
